version: '3'
services:
  redis:
    container_name: redis
    image: redis
    networks:
      - twenti
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - twenti
  twenti-auth:
    container_name: twenti-auth
    image: twenti-auth
    build:
      context: ""
      dockerfile: ./Dockerfile
    expose:
      - 8080
    ports:
      - "8080:3000"
    networks:
      - twenti
    restart: always
    #    environment:
    #      SERVICE_NAME: eureka
    #      PROFILE: ${PROFILE}
    #      CONFIG_SERVER_URI: http://config:8888
networks:
  twenti:
    external: true